export const CATEGORIES = {
  Expenses: [
    "Food",
    "Load",
    "House cleaning",
    "Entertainment",
    "Laundry",
    "Home supplies",
    "Car parking",
    "Gas",
    "Beauty",
    "Health",
    "Transportation",
    "Gift",
    "Shopping (clothes/bag/shoes)",
    "Make-up",
    "Grocery",
    "Travel",
  ],
  Bills: [
    "Regalia (Electicity, water, gym)",
    "Regalia Rent (House & Parking)",
    "RCBC Insuranece",
    "iPhone 14 Installment",
    "AirPods Pro 2 Installment",
    "Norman Insurance",
    "PLDT Internet",
    "Zsa Insurance",
  ],
  Subscriptions: [
    "YouTube",
    "Spotify",
    "Disney+",
    "Prime Video",
    "Grab Subscription",
  ],
  Income: ["Bridge Salary", "Mosaic Salary", "Receivable", "Other Income"],
  "Savings & Investments": [],
};
